on: push
jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: |
          npm install-ci-test
          cd ./build/
          echo "{ \"main\": \"./main.mjs\" }" > ./package.json
          ../node_modules/.bin/electron-packager . \"Le-draw\" --icon ../assets/logo.icns --overwrite
          cd ./Le-draw-darwin-arm64/
          zip --recurse-paths --symlinks ./Le-draw.app.zip ./Le-draw.app
      - uses: actions/upload-artifact@main
        with:
          path: ./build/Le-draw-darwin-arm64/Le-draw.app.zip
          name: Le-draw.app.zip
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@master
        with:
          files: ./build/Le-draw-darwin-arm64/Le-draw.app.zip
