on: push
jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: |
          npm install-ci-test
          cd ./build/
          echo "{ \"main\": \"./main.mjs\" }" > ./package.json
          electron-packager . \"Lê-draw\" --icon ../assets/logo.icns --overwrite
      - uses: actions/upload-artifact@main
        with:
          path: ./kill-the-newsletter--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
          name: kill-the-newsletter--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@master
        with:
          files: ./**/*.*
